### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/dissertation#3]
### Overall
- [x] 1 line dedication
- [x] min. 3 sentence acknowledgement 
- [x]  biosketch at the end
- [x] Ecology paper (chap 2) footnote
- [x] Peerj paper (chap 3) footnote
- [x] eco apps / biorxiv (chap 4) footnote (?)
- [x] need to knock down the dpi, and thus filesize, on all images, especially NPN-LTER comparions appendix
- [x] make all urls clickable hyperlinks
- [ ] 
- [ ] 
- [ ] 
- [ ] 

### Chapter 1 (introduction)

- [x]  write
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by sdtaylor** [comment]
### Chapter 2 - Appendix A (NPN-LTER comparison)

- [ ]  ~We -> I throughout (?)~
- [x]  un-italicize all model names throughout
- [x]  change appendix images text to reference correct figure number in main text
- [x] make smaller fonts in large appendix tables (just get ride  of number phenophase column)
    spp names are now wrapped badly, but whatever
- [x] appedix/supplement figs: reference new figures in some of the legends
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by sdtaylor** [comment]
### Chapter 3 - Appendix B (estimators)

- [x]  import final figures
- [x]  software references
- [x] import final published version
- [ ] if they complain about Appendix B heading having a blank page, I think it's cause the first thing is an image. So just need to add some initial supplemental text. 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by sdtaylor** [comment]
### Chapter 4 (forecast infrastructure) - Appendix C

- [x]  import appendix/supplement (need tables)
- [x]  change all primary fig references
- [x]  change all supplement fig references
- [x]  import final figures
- [x]  references all figures correctly in main text
- [x]  references all figures correctly in supplement
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

Table C-1 = list of all the models
Table C-2 = list of species used in evaluation

version first put onto overleaf: https://github.com/sdtaylor/phenology_forecasts/blob/4238e961f3a0b385d7ffe84dc5e164d13c13a508/methods_manuscript/main.md

**Comment by sdtaylor** [comment]
### Chap 5 - Conclusion

- [x] write
- [ ] 
- [ ] 
- [ ]

**Comment by sdtaylor** [comment]
accepted!
